# -----------------------------------------------------
# Monitor Setup
# name: "Custom monitor via HDMI"
# -----------------------------------------------------

monitor=HDMI-A-2,preferred,auto,1,mirror,eDP-1 # mirror to eDP-1 (default)

