#!/bin/bash

options=(
	style=round
	width=8.0
	hidpi=on
	# active_color=0xf42fb2eb # blue
	# active_color=0xffffbe33 # orange
  # active_color=0xffe2e2e3
	# inactive_color=0xff414550
  blacklist="iPhone Mirroring"
)

borders "${options[@]}"
